import React from 'react';

import type { Metadata } from 'next';
import 'bastianparedes/styles/global.css';
import 'bastianparedes/styles/normalize.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="es">
      <head>
        <meta charSet="utf-8" />
        <link href="/favicon.ico" rel="icon" />
        <title>Bastián Paredes</title>
      </head>
      <body>{children}</body>
    </html>
  );
};

export default Layout;
